version: "3.6"
services:
  front:
    image: innovation/spdoc_web:v1.0.0
    container_name: spdoc-frontend
    restart: always
    networks:
      - spdocnetwork
    ports:
      - "3002:80"
    environment:
      APPLICATION_PORT: 3002
      NODE_ENV: prod
networks:
  spdocnetwork:
    external:
      name: spdoc-project-network
